---
image: gebish/ci:v1

variables:
  GRADLE_USER_HOME: .gradle-home

stages:
  - main check
  - secondary checks
  - first cross browser
  - second cross browser
  - upload
  - trigger builds

modules:
  stage: main check
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .gradle-home
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - build/reports
  script:
    - ./gradlew --no-daemon -p module -Pci check --continue

compatibility:
  stage: main check
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .gradle-home
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - build/reports
  script:
    - ./gradlew --no-daemon -p compatibility -Pci check --continue

integrations:
  stage: secondary checks
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .gradle-home
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - build/reports
  script:
    - ./gradlew --no-daemon -p integration -Pci check --continue

manual:
  stage: secondary checks
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .gradle-home
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - build/reports
  script:
    - Xvfb :99 -screen 1 1280x1024x16 -nolisten tcp -fbdir /var/run > /dev/null 2>&1 &
    - export DISPLAY=:99
    - ./gradlew --no-daemon -Pci :doc:manual-snippets:check :doc:manual:build

site:
  stage: secondary checks
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .gradle-home
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - build/reports
  script:
    - ./gradlew --no-daemon -p doc/site -Pci check

saucelabs:
  stage: first cross browser
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .gradle-home
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - build/reports
  script:
    - ./gradlew --no-daemon -Pci allSauceLabsTests

non-ie:
  stage: first cross browser
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .gradle-home
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - build/reports
  script:
    - ./gradlew --no-daemon -Pci nonIeBrowserStackTests

ie:
  stage: second cross browser
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .gradle-home
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - build/reports
  script:
    - ./gradlew --no-daemon -Pci ieBrowserStackTests

upload:
  only: master
  stage: upload
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .gradle-home
  script:
    - ./gradlew --no-daemon -Pci uploadArchives

publish-site:
  only: master
  stage: upload
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/gebish.git
    - git push -f heroku master

triggger-example-projects:
  only: master
  stage: trigger builds
  script:
    - "curl -X POST -F token=f4906c9c437605db34f866ccaa7dfb -F ref=latest https://gitlab.com/api/v4/projects/3302923/trigger/pipeline"
    - "curl -X POST -F token=8ee359a96d5892d6d36f5a7f2482ed -F ref=latest https://gitlab.com/api/v4/projects/3300893/trigger/pipeline"
    - "curl -X POST -F token=23604413c25eb05e17eea588d06d2e -F ref=latest https://gitlab.com/api/v4/projects/3264749/trigger/pipeline"