version: 2
jobs:
  build:
    working_directory: ~/geb
    docker:
      - image: gebish/ci:v1
        environment:
          GRADLE_OPTS: -Xmx512m
          JAVA_OPTS: -Dfile.encoding=utf8
    steps:
      - checkout
      - restore_cache:
          keys:
            - ie-browserstack-{{ .Branch }}
            - non-ie-browserstack-{{ .Branch }}
            - saucelabs-{{ .Branch }}
            - site-{{ .Branch }}
            - manual-{{ .Branch }}
            - integrations-{{ .Branch }}
            - modules-{{ .Branch }}
      - run:
          name: Check modules
          command: |
            ./gradlew --no-daemon -p module -Pci -g .gradle-home check --continue
            ./gradlew --no-daemon -p compatibility -Pci -g .gradle-home check --continue
      - save_cache:
          key: modules-{{ .Branch }}
          paths:
            - ".gradle-home"
      - run:
          name: Check integrations
          command: |
            ./gradlew --no-daemon -p integration -Pci -g .gradle-home check --continue
      - save_cache:
          key: integrations-{{ .Branch }}
          paths:
            - ".gradle-home"
      - run:
          name: Check manual
          command: |
            Xvfb :99 -screen 1 1280x1024x16 -nolisten tcp -fbdir /var/run > /dev/null 2>&1 &
            export DISPLAY=:99
            ./gradlew --no-daemon -Pci -g .gradle-home :doc:manual-snippets:check :doc:manual:build
      - save_cache:
          key: manual-{{ .Branch }}
          paths:
            - ".gradle-home"
      - run:
          name: Check site
          command: |
            ./gradlew --no-daemon -p doc/site -Pci -g .gradle-home check
      - save_cache:
          key: site-{{ .Branch }}
          paths:
            - ".gradle-home"
      - run:
          name: Cross browser tests at SauceLabs
          command: |
            ./gradlew --no-daemon -Pci -g .gradle-home allSauceLabsTests
      - save_cache:
          key: saucelabs-{{ .Branch }}
          paths:
            - ".gradle-home"
      - run:
          name: Non-IE tests at BrowserStack
          command: |
            ./gradlew --no-daemon -Pci -g .gradle-home nonIeBrowserStackTests --info
      - save_cache:
          key: non-ie-browserstack-{{ .Branch }}
          paths:
            - ".gradle-home"
      - run:
          name: IE tests at BrowserStack
          command: |
            ./gradlew --no-daemon -Pci -g .gradle-home ieBrowserStackTests --info
      - save_cache:
          key: ie-browserstack-{{ .Branch }}
          paths:
            - ".gradle-home"